name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  gcc-build-test:
    name: gcc build & test
    runs-on: self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install -y python3-pip
      - run: pip install -r tools/python_api/requirements_dev.txt

      - name: build
        run: CC=gcc-11 bazel build --cxxopt='-std=c++2a' --cxxopt='-O3' //...:all

      - name: test
        run: CC=gcc-11 bazel test --test_output=errors --cxxopt='-std=c++2a' --cxxopt='-O3' //...:all

  clang-build-test:
    name: clang build & test
    runs-on: self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install -y python3-pip
      - run: pip install -r tools/python_api/requirements_dev.txt

      - name: build
        run: CC=clang-14 bazel build --cxxopt='-std=c++2a' --cxxopt='-O3' //...:all

      - name: test
        run: CC=clang-14 bazel test --test_output=errors --cxxopt='-std=c++2a' --cxxopt='-O3' //...:all

  clang-formatting-check:
    name: clang-formatting-check
    runs-on: self-hosted-testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Sarcasm/run-clang-format
          path: run-clang-format
      - run: sudo apt install -y clang-format-11
      - run: python3 run-clang-format/run-clang-format.py --clang-format-executable /usr/bin/clang-format-11 -r src/
      - run: python3 run-clang-format/run-clang-format.py --clang-format-executable /usr/bin/clang-format-11 -r test/

  benchmark:
    name: benchmark
    runs-on: self-hosted-himrod
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y python3-pip && sudo apt install -y sqlite3
      - run: pip3 install -r tools/python_api/requirements_dev.txt

      - name: build
        run: CC=gcc-9 bazel build --cxxopt='-std=c++2a' --cxxopt='-O3' //...:all

      - name: benchmark
        run: python3 benchmark/benchmark_runner.py --dataset ldbc-sf100
